#!/usr/bin/env bash

if command -v swayidle > /dev/null
then
  swayidle -w \
    timeout 300 swaylock \
    timeout 600 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    before-sleep swaylock
fi
