#!/usr/bin/env bash

DOTFILES_ROOT=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

printf "${DOTFILES_ROOT} - starting installation\n"

printf "${DOTFILES_ROOT} - binding dotfiles\n"

DOTFILES=(fonts asdf fzf)

if command -v zsh > /dev/null
then
  DOTFILES+=(zsh zshrc)
fi

if command -v vim > /dev/null
then
  DOTFILES+=(vim vimrc)
fi

if command -v tmux > /dev/null
then
  DOTFILES+=(tmux tmux.conf)
fi

for dotfile in "${DOTFILES[@]}"
do
  if [ -h "${HOME}"/."${dotfile}" ]
  then
    printf "${HOME}/.${dotfile} exists\n"
  else
    ln -s "${DOTFILES_ROOT}"/"${dotfile}" "${HOME}"/."${dotfile}"
    printf "${HOME}/.${dotfile} linked\n"
  fi
done

printf "${DOTFILES_ROOT} - synchronizing submodules\n"

(cd "${DOTFILES_ROOT}" && git submodule update --quiet --init --recursive --depth 1)

printf "${DOTFILES_ROOT} - "
$DOTFILES_ROOT/fzf/install --bin

printf "${DOTFILES_ROOT} - installation finished\n"
