#!/usr/bin/env bash

# Change directory to this script location
cd "$(dirname "${BASH_SOURCE[0]}")"

printf "Setting up dotfiles\n"

DOTFILES=(fonts asdf fzf Xdefaults)

# Verifying available commands / programs
if command -v zsh > /dev/null
then
  DOTFILES+=(zsh zshrc)
fi

if command -v vim > /dev/null
then
  DOTFILES+=(vim vimrc)
fi

if command -v tmux > /dev/null
then
  DOTFILES+=(tmux tmux.conf)
fi

modules=$(git config --file .gitmodules --get-regexp path | awk '{ print $2 }')

for dotfile in "${DOTFILES[@]}"
do
  printf "${dotfile}\n"

  if [ -h "${HOME}/.${dotfile}" ]
  then
    printf "  - Already exists: ${HOME}/.${dotfile}\n"
  else
    ln -s "${PWD}/${dotfile}" "${HOME}/.${dotfile}"
    printf "  - Link created: ${HOME}/.${dotfile}\n"
  fi

  for module in $modules
  do
    if [[ $module = *"${dotfile}"* ]]
    then
      printf "  - Downloading module: ${module}\n"
      if [[ $* == *--upgrade* ]]
      then
        git submodule update --remote --quiet --init --depth 1 ${PWD}/${module}
      else
        git submodule update --quiet --init --depth 1 ${PWD}/${module}
      fi
      printf "  - Download complete\n"
    fi
  done
done

# Post-download setup
$PWD/fzf/install --bin

printf "Setup completed\n"
