require('nvim-treesitter.configs').setup {
  ensure_installed = {
    "bash",
    "c",
    "cmake",
    "dockerfile",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "hcl",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "passwd",
    "proto",
    "python",
    "query",
    "sql",
    "terraform",
    "vim",
    "vimdoc",
  },
  highlight = { enable = true },
}
