# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = """\
$character\
"""

# move the rest of the prompt to the right
right_format = """\
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$jobs\
$nix_shell\
$conda\
$container\
$aws\
$gcloud\
$openstack\
$kubernetes\
$python\
$rust\
$go\
$nodejs\
$php\
$java\
$elm\
$ruby\
$crystal\
$swift\
$julia\
$custom\
$shell\
$memory_usage\
$cmd_duration\
$terraform\
$line_break\
"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❝](bold blue)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[⚠](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[aws]
disabled = false
symbol = ':'
format = '[($profile)$symbol]($style)'

[nodejs]
disabled = true

[kubernetes]
disabled = false
format = ':[$namespace@[$context󱃾](bold blue)](blue) '

[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:[0-9a-z\\-]+:[0-9]+:cluster/(?P<cluster>[\\w-]+)"
context_alias = "$cluster  "

[git_branch]
ignore_branches = ['master', 'main']
format = '[$branch(:$remote_branch)$symbol]($style)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
untracked = ''
modified = '󰀨'
