# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = """$character"""

# move the rest of the prompt to the right
right_format = """$all"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❝](bold blue)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[⚠](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[aws]
disabled = true

[kubernetes]
disabled = false
format = '[\[ $namespace[@$context](bold blue)\]](blue) '

[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:[0-9a-z\\-]+:[0-9]+:cluster/(?P<cluster>[\\w-]+)"
context_alias = "$cluster  "
