#!/usr/bin/env bash

systemctl --user --quiet is-active hyprsunset
if [ $? -eq 0 ]
then
  systemctl --user stop hyprsunset
  pkill -SIGRTMIN+12 waybar
else
  systemctl --user start hyprsunset
  pkill -SIGRTMIN+12 waybar
fi
