#!/usr/bin/env sh

source "$XDG_DATA_HOME/dotfiles/colors"

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 all:0:20       \
    mouse_follows_focus          off            \
    focus_follows_mouse          autofocus      \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               on             \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        1.0            \
    window_opacity               off            \
    insert_feedback_color        $COLOR_RED     \
    active_window_border_color   $COLOR_BLUE    \
    normal_window_border_color   $COLOR_BG0     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   08             \
    layout                       bsp            \
    mouse_modifier               cmd            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^(Calculator|Software Update|System Preferences|System Settings|Archive Utility|Stats)$" manage=off

yabai -m signal --add \
  event=window_created \
  action="yabai -m window --focus \$YABAI_WINDOW_ID"

yabai -m signal --add \
  event=window_destroyed \
  action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
