alias l='eza -lha'
alias ll='eza -1a'
alias lc='wc -l'
alias v='nvim'
alias jv='nvim -c "set syntax=json"'
alias todo='nvim -c "set nonumber" ~/todo.md'
alias envfile='env $(cat .env | xargs)'
alias ssh='TERM=xterm-256color ssh'
alias gitpatch="git tag | sort -Vr | head -n 1 | awk -F. '{\$3++; print \$0}' | sed 's/ /./g'"
alias asciicast2gif='docker run --rm -v $PWD:/data asciinema/asciicast2gif'
