#!/usr/bin/env bash

$XDG_CONFIG_HOME/sway/lib/bumblebee-status/bumblebee-status \
  --modules \
    git \
    pasink \
    pasource \
    brightness \
    load \
    battery \
    time \
  --parameters \
    time.format="%F %T" \
  --theme gruvbox-powerline
